# Layer configuration for meta-trainerdemo
# This is the layer we build throughout the Yocto training.

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-trainerdemo"
BBFILE_PATTERN_meta-trainerdemo = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-trainerdemo = "10"

# This layer is compatible with the Scarthgap (5.0) release series.
LAYERSERIES_COMPAT_meta-trainerdemo = "scarthgap"

# Tell BitBake the minimum layer dependencies (optional but good practice)
LAYERDEPENDS_meta-trainerdemo = "core"
